In [4]:
import numpy as np

##### Create Numpy Arrays from Python lists

In [5]:
a = np.array([1,2,3,4])
print(a)
np.array([1,2,3])

[1 2 3 4]


array([1, 2, 3])

In [6]:
# use only one datatype
np.array([3.14, 2, 2]) 

array([3.14, 2.  , 2.  ])

In [7]:
#ep kieu
np.array([1.2,3,2], dtype = 'int16')

array([1, 3, 2], dtype=int16)

In [8]:
a1 = np.array([[1,2,3],[1,2,3]])
type(a)

numpy.ndarray

In [9]:
# so dong va so cot
a1.shape

(2, 3)

In [10]:
# so chieu 
a1.ndim

2

In [11]:
# kich co cua mang 
a1.size

6

##### Create Numpy Arrays from Scratch

In [12]:
# zeros 
np.zeros([2,4], dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [13]:
#ones
np.ones([2,3], dtype = float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# create an array  filled with a linear sequence 
# starting, ending, stepping are changable
# similar to range()
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
# full 
np.full([3,6], 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9, 6.9]])

In [16]:
# create an array of n values evenly spaced between a,b
np.linspace(0, 20, 20)

array([ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
        5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
       10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
       15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ])

In [17]:
# create an array of random values
np.random.random([4,4])

array([[0.59311012, 0.41443099, 0.41516047, 0.40501108],
       [0.28130143, 0.40731319, 0.11789738, 0.51720787],
       [0.4758209 , 0.85842074, 0.73812814, 0.03779584],
       [0.54837987, 0.71718928, 0.30893502, 0.74694047]])

In [18]:
# seed for reproducibility
np.random.seed(0)
np.random.random([4,4])

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [19]:
# normal( mean, std, shape)
np.random.normal(0, 2,[3,3])

array([[ 0.88772647,  0.66734865,  2.98815815],
       [-0.41031653,  0.6261354 , -1.70819148],
       [-5.10597963,  1.30723719,  1.7288724 ]])

In [20]:
np.random.randint(1,10,[3,3])

array([[8, 3, 1],
       [1, 5, 6],
       [6, 7, 9]], dtype=int32)

In [21]:
# block matrix
np.random.rand(4,4,4) 

array([[[0.616934  , 0.94374808, 0.6818203 , 0.3595079 ],
        [0.43703195, 0.6976312 , 0.06022547, 0.66676672],
        [0.67063787, 0.21038256, 0.1289263 , 0.31542835],
        [0.36371077, 0.57019677, 0.43860151, 0.98837384]],

       [[0.10204481, 0.20887676, 0.16130952, 0.65310833],
        [0.2532916 , 0.46631077, 0.24442559, 0.15896958],
        [0.11037514, 0.65632959, 0.13818295, 0.19658236],
        [0.36872517, 0.82099323, 0.09710128, 0.83794491]],

       [[0.09609841, 0.97645947, 0.4686512 , 0.97676109],
        [0.60484552, 0.73926358, 0.03918779, 0.28280696],
        [0.12019656, 0.2961402 , 0.11872772, 0.31798318],
        [0.41426299, 0.0641475 , 0.69247212, 0.56660145]],

       [[0.26538949, 0.52324805, 0.09394051, 0.5759465 ],
        [0.9292962 , 0.31856895, 0.66741038, 0.13179786],
        [0.7163272 , 0.28940609, 0.18319136, 0.58651293],
        [0.02010755, 0.82894003, 0.00469548, 0.67781654]]])

#### Array Indexing & Slicing 

 One-dimensional subarray

In [22]:
x1 = np.random.randint(20, size = 6)
x1

array([ 3,  2, 11, 13, 16,  8], dtype=int32)

In [23]:
x1[2], x1[3]

(np.int32(11), np.int32(13))

 Multi-dimensional array

In [24]:
x2 = np.random.randint(20,size =[3,3])
x2

array([[ 8, 19,  8],
       [ 2,  3, 12],
       [14,  0,  4]], dtype=int32)

In [25]:
x2[2,2] = 2
x2

array([[ 8, 19,  8],
       [ 2,  3, 12],
       [14,  0,  2]], dtype=int32)

Slicing

In [26]:
x1 

array([ 3,  2, 11, 13, 16,  8], dtype=int32)

In [27]:
# rev = x1[start:stop:step]
rev = x1[2:5]
rev 

array([11, 13, 16], dtype=int32)

In [28]:
rev2 = x1[2:5:2]
rev2

array([11, 16], dtype=int32)

In [29]:
# another matrix
x2 

array([[ 8, 19,  8],
       [ 2,  3, 12],
       [14,  0,  2]], dtype=int32)

In [30]:
# any = x2[rows , collumns]
any = x2[:2, :2]
any

array([[ 8, 19],
       [ 2,  3]], dtype=int32)

Reshaping of Arrays & Transpose

In [31]:
grid = np.arange(1,10)
grid.shape

(9,)

In [32]:
grid.reshape([3,3])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
x = np.array([1,2,3])

In [34]:
x.reshape([3,1])

array([[1],
       [2],
       [3]])

In [35]:
x1 = np.random.randint(0,10,[3,2])
x1

array([[3, 6],
       [9, 8],
       [0, 8]], dtype=int32)

In [36]:
x1.reshape([1,6])

array([[3, 6, 9, 8, 0, 8]], dtype=int32)

In [37]:
x1.T

array([[3, 9, 0],
       [6, 8, 8]], dtype=int32)

Array concatenation and Splitting

In [38]:
tmp1 = np.array([1,2,3,4])
tmp2 = np.array([1,2,3])
tmp3 = np.ones([3],dtype = int)
tmp1, tmp2

(array([1, 2, 3, 4]), array([1, 2, 3]))

In [39]:
print(np.concatenate((tmp1,tmp2)))
np.concatenate((tmp3,tmp2))

[1 2 3 4 1 2 3]


array([1, 1, 1, 1, 2, 3])

In [40]:
#vertical stack 
x = np.random.randint(0,10,[2,3])
con = np.random.randint(0,10,[1,3])
np.vstack([x,con])

array([[5, 9, 0],
       [9, 6, 5],
       [3, 1, 8]], dtype=int32)

In [41]:
#horizontally stack the arrays 
x = np.random.randint(0,10,[3,3])
con = np.random.randint(0,10,[3,1])
np.hstack([x,con])

array([[0, 4, 9, 2],
       [6, 5, 7, 8],
       [8, 8, 9, 6]], dtype=int32)

Splitting of arrays

In [42]:
x = np.array([1,2,3,4,2,4,55])
a,b,c = np.split(x,[3,5])
a,b,c

(array([1, 2, 3]), array([4, 2]), array([ 4, 55]))

## Broadcasting and Vectorized operations
Broadcasting is simply a set of a rules for appling  binary ufuncs (e.g. additon, subtraction, multiplication, etc.) on the arrays of different sizes.

In [45]:
a = np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [ ]:
a = a + 1 #Broadcasting 
a 


array([1, 3, 5, 7, 9])

In [46]:
a = np.array([1,2])
b = np.array([
    [2,3],
    [3,1]
])
c = a + b 
c

array([[3, 5],
       [4, 3]])

#### Manipulating & Compare Arrays
Aggregation 

Aggreation = performing the same operation on a number of things 

In [53]:
list_number = [1,2,3]
l1 = np.array(list_number)
l1

array([1, 2, 3])

In [57]:
np.sum([l1]) # numpy sum

np.int64(6)

In [58]:
sum(l1) # python sum

np.int64(6)

In [66]:
#Create a massive Numpy array 
massive_array = np.random.randint(0,100001,[100,100])
massive_array.size

10000

In [67]:
massive_array.shape

(100, 100)

In [74]:
%timeit sum(massive_array)

86.6 μs ± 4.38 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [75]:
%timeit np.sum(massive_array)

15.6 μs ± 1.22 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [76]:
np.mean(massive_array)

np.float64(49740.8083)

In [77]:
np.max(massive_array)

np.int32(99987)

In [78]:
np.min(massive_array)

np.int32(14)

In [79]:
# std = standard Deviation do lech chuan 
# variance = phuong sai 
dog_height = [600,470,170,430,300]
dog_height = np.array(dog_height)
np.std(dog_height)

np.float64(147.32277488562318)

In [80]:
np.var(dog_height)

np.float64(21704.0)

In [83]:
np.sqrt(np.var(dog_height))

np.float64(147.32277488562318)

### Sorting Arrays
np.sort uses an quicksort algorithm

In [84]:
x = np.array([1,23,1,4,1,4])
np.sort(x)

array([ 1,  1,  1,  4,  4, 23])

In [85]:
# A related function is argsort, which is instead returns the indices of the sorted elements:
np.argsort(x)

array([0, 2, 4, 3, 5, 1])

### Sorting along rows or columns
NumPy's sorting algorithm is the ability to sort along specific rows or columns of a multidimentional array using the axis argument

In [86]:
np.random.seed(42)
MatA = np.random.randint(0,10,[3,3])
MatA

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7]], dtype=int32)

In [ ]:
np.sort(MatA, axis = 0 ) # columns 

array([[2, 3, 7],
       [4, 6, 7],
       [6, 6, 9]], dtype=int32)

In [ ]:
np.sort(MatA, axis = 1) # rows 

array([[3, 6, 7],
       [4, 6, 9],
       [2, 6, 7]], dtype=int32)

###  Linear Algebra

In [91]:
MatB = np.random.randint(1,10,[3,2])
MatB

array([[5, 2],
       [8, 6],
       [2, 5]], dtype=int32)

In [ ]:
MatA.dot(MatB) # tich 2 vector 

array([[68, 65],
       [86, 89],
       [72, 75]], dtype=int32)

In [ ]:
MatA @ MatB # same to above 

array([[68, 65],
       [86, 89],
       [72, 75]], dtype=int32)

In [95]:
MatB.T @ MatA

array([[ 66,  75, 121],
       [ 46,  72, 103]], dtype=int32)

### Dot product example 

In [97]:
# Number of jars sold
np.random.seed(0)
sales_amounts = np.random.randint(20,size = (5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [ ]:
# Create weekly_sales DataFrame 
import pandas as pd
weekly_sales = pd.DataFrame(sales_amounts, index = ["Monday", "Tuesday","Wednesday", "Thursday", "Friday"], 
                            columns = ["Almond Butter", 'Peanut Butter', "Cashew Butter"])
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Monday                12             15              0
Tuesday                3              3              7
Wednesday              9             19             18
Thursday               4              6             12
Friday                 1              6              7

In [102]:
# Create a price array 
prices = np.array([10,8,12])
butter_prices = pd.DataFrame(prices.reshape(1,3), index = ["Prices"], columns = ["Almond Butter", 'Peanut Butter', "Cashew Butter"])

In [103]:
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Prices             10              8             12

In [104]:
res = weekly_sales @ butter_prices.T

In [111]:
weekly_sales["Total_price"] = res 
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total_price
Monday                12             15              0          240
Tuesday                3              3              7          138
Wednesday              9             19             18          458
Thursday               4              6             12          232
Friday                 1              6              7          142

In [114]:
np.sum(weekly_sales["Total_price"])

np.int64(1210)